### ISSUE TITLE
make it clear in readme that this runs on ALL PowerShell versions

### ISSUE THREAD

**Issue by iricigor** [mklement0/ClipboardText#1]
Initially, I was not sure if this module runs on Windows PowerShell v.5. I tested it and it works fine.

This should be clear from `readme.md`, because that means module can be used in universal PowerShell scripts. Universal PowerShell scripts are the ones which run on both Windows PowerShell and PowerShell Core.

**Comment by mklement0** [comment]
@iricigor. Thanks; it was implied by the old text, but I've just updated the introductory section to make it clearer and use the term _universal script_. Let me know if the wording makes sense.
