### ISSUE TITLE
Remove dependency on Windows Script Host

### ISSUE THREAD

**Issue by redoz** [mklement0/ClipboardText#3]
I tried using this on windows and I get an error because the script host has been disabled through a domain policy by our IT department. Would it not be possible to P/Invoke relevant APIs on windows instead?

**Comment by mklement0** [comment]
Good suggestion, @redoz - I'll look into it. You'd invariably pay a performance penalty on first invocation in a given session, however.

**Comment by mklement0** [comment]
@redoz: [Version 1.5](https://www.powershellgallery.com/packages/ClipboardText/0.1.5) now uses a helper type (compiled on demand) for getting clipboard text via the Windows API - no more WSH use.

**Comment by redoz** [comment]
@mklement0 that's fantastic, thank you!

**Comment by mklement0** [comment]
My pleasure; in my tests it works - do let me know if it doesn't. Remember that on first invocation in a session you'll pay the performance penalty for on-demand compilation.

**Comment by redoz** [comment]
I don't think anyone uses powershell because it's fast :) 
I'll give it a try on Monday when I'm back at work. Have a great weekend!

**Comment by mklement0** [comment]
:) - you too.

**Comment by redoz** [comment]
@mklement0 Just gave this a try and it seems to work fine now, thanks again.

**Comment by mklement0** [comment]
Glad to hear it, @redoz; my pleasure.
