### ISSUE TITLE
CMD message if working directory is a UNC path

### ISSUE THREAD

**Issue by sba923** [mklement0/ClipboardText#4]
Thanks for this awesome module! Removes one more reason for not switching to PowerShell Core 6.x ;-)

I'd like to report a relatively minor issue.

If the current working directory is a UNC path, invoking Set-ClipboardText results in a message from CMD:

`PS //pnjnas/public/olddiscs> (pwd).ProviderPath`
`\\pnjnas\public\olddiscs`
`PS //pnjnas/public/olddiscs> "foo" | Set-ClipboardText`
`'\\pnjnas\public\olddiscs'`
`CMD.EXE was started with the above path as the current directory.`
`UNC paths are not supported.  Defaulting to Windows directory.`

The solution is quite simple: wrap the invocation of CMD in a piece of code that preserves the current working directory, switches to some location on a non-network drive, and last restores the initial working directory, something like:

`$oldpwd = (pwd).path`
`cd c:/ # ideal is to find a local drive instead of hardcoding c:`
`cmd.exe /c clip.exe '<' $tmpFile`
`cd $oldpwd`

**Comment by mklement0** [comment]
I appreciate the nice feedback and the bug report plus suggestion fix, @sba923.

I'll fix this soon.

**Comment by mklement0** [comment]
Just published v0.1.6, which should fix the issue (I've used as the guaranteed-to-be-local `"$env:SystemDrive\"` location to temporarily switch to).

**Comment by sba923** [comment]
Test OK in PowerShell Core 6.1

Great job!
