### ISSUE TITLE
With Windows PowerShell, complains about missing xclip the first it's used if StrictMode is in effect

### ISSUE THREAD

**Issue by sba923** [mklement0/ClipboardText#5]
My PowerShell profile invokes 

`Set-StrictMode -Version Latest`

As a side effect, the first time I use the module in a PS session (i.e. when the module gets auto-loaded), I get a message telling me that "xclip" is not installed... whereas I'm running Windows PowerShell 5.1 on Windows 10 ;-)

Here's the culprit: CheckPrereqs.ps1 tests the value of $IsLinux, which doesn't exist in Windows PowerShell. If StrictMode is not in effect, the test works, because $IsLinux silently evaluates to $null.

But if StrictMode is in effect, the test fails...

**Comment by mklement0** [comment]
Good find, and thanks for the detailed pointers - just published v0.1.7 with a fix.

As an aside:

Modules that don't have `ScriptsToProcess` entries won't be affected, but I expect that many a script will break if you spring a global `Set-StrictMode -Version Latest` on it (unless these scripts all manage their own strict mode).

There is a - languishing - RFC that proposes introduction of a _lexical_ strict mode, that would avoid such problems - see https://github.com/PowerShell/PowerShell-RFC/blob/master/1-Draft/RFC0003-Lexical-Strict-Mode.md

**Comment by sba923** [comment]
Fix tested with Windows PowerShell 5.1 and PowerShell Core 6.1. 

Good job!

**Comment by sba923** [comment]
I have an unrelated question (posted here so that the discussion is available to others).

You write:

`$iswin = ($null, 'Desktop' -contains $PSVersionTable.PSEdition)`

instead of just:

`$iswin = 'Desktop' -contains $PSVersionTable.PSEdition`

Can you explain why?

On a platform where $PSVersionTable doesn't have a PSEdition member, wouldn't that raise an exception anyway?
